name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # auth w/JSR
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: setup deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.2.6
      - name: publish to jsr
        run: deno publish
